export enum DeltaType {
    NO_EXECUTION = "NO_EXECUTION",
    PERFECT_MATCH = "PERFECT_MATCH",
    LATE = "LATE",
    EARLY = "EARLY",
    UNDER_DELIVERED = "UNDER_DELIVERED",
    OVER_DELIVERED = "OVER_DELIVERED",
    DEVIATION = "DEVIATION"
}
