export enum RoleInOrder {
    ORDERER = "ORDERER",
    PAYER = "PAYER",
    RECEIVER = "RECEIVER",
    EXECUTOR = "EXECUTOR",
    DELIVERY_CONTACT = "DELIVERY_CONTACT",
    PICKUP_AUTHORIZED = "PICKUP_AUTHORIZED"
}
